str = "    Hello everyone and welcome to    the day 04 of \'Learning Python\' "

print(str.upper())
print(str.lower())
print(str.strip())
print(str.rstrip())
print(str.replace("Hello", "Welcome"))
print(str.split(" "))
print(str.capitalize())
print(str.center(70))
print(str.count("e"))
print(str.endswith("\'"))
print(str.find("\'"))
print(str.index("04"))
print(str.isalnum())
print(str.isalpha())
print(str.islower())
print(str.isprintable())
print(str.isspace())
print(str.istitle())
print(str.isupper())
print(str.startswith("Hello"))
print(str.swapcase())
print(str.title())